const Subject = require('../models/Subject')
const Course = require('../models/Course')

const subjects = [
    { code: 'ASBI', name: 'Astrobiologia' },
    { code: 'BIOI', name: 'Bioinformatics' },
    { code: 'KABI', name: 'Biokemia' },
    { code: 'BKEM', name: 'Biokemia' },
    { code: 'BIOL', name: 'Biologia' },
    { code: 'FYGE', name: 'Biologia' },
    { code: 'XBIO', name: 'Biologia' },
    { code: 'BIOT', name: 'Biolääketiede' },
    { code: 'FALL', name: 'Biolääketiede' },
    { code: 'BIMA', name: 'Biomedical Imaging' },
    { code: 'DIBT', name: 'Biotekniikka' },
    { code: 'EKOL', name: 'Ekologia ja evoluutiobiologia' },
    { code: 'DEKE', name: 'Elintarvikekehitys' },
    { code: 'FOOD', name: 'Elintarvikekemia' },
    { code: 'FFYS', name: 'Fysiikka' },
    { code: 'GEOL', name: 'Geologia' },
    { code: 'GMIN', name: 'Geologia ja mineralogia' },
    { code: 'KEMI', name: 'Kemia' },
    { code: 'MAAN', name: 'Maantiede' },
    { code: 'MATE', name: 'Matematiikka' },
    { code: 'SMAT', name: 'Sovellettu matematiikka' },
    { code: 'TFYS', name: 'Teoreettinen fysiikka' },
    { code: 'TKO_', name: 'Tietojenkäsittelytiede' },
    { code: 'DTEK', name: 'Tietotekniikka' },
    { code: 'TILM', name: 'Tilastotiede' },
    { code: 'YMPS', name: 'Ympäristötiede' }
]
const courses = [
    { code: 'ASBI0010', name: 'Aikavaellus' },
    { code: 'ASBITEMA', name: 'Astrobiologian temaattinen opintokokonaisuus 2018 - 2020' },
    { code: 'ASBI0007', name: 'Astrobiologian kirjallisuustentti' },
    { code: 'ASBI0009', name: 'Astrobiologian harjoitusaine' },
    { code: 'ASBI0004', name: 'Kansainvälinen astrobiologian kokous I' },
    { code: 'ASBI0003', name: 'Kansallinen astrobiologian kokous' },
    { code: 'ASBI0005', name: 'Astrobiologian kesäkoulu' },
    { code: 'ASBI0006', name: 'Astrobiologian opintopäiväkirja' },
    { code: 'BIOI2250', name: 'Introduction to Programming' },
    { code: 'BIOI2241', name: 'Introduction to Statistical Analysis' },
    { code: 'BIOI2260', name: 'Introduction to Computer Science' },  
    { code: 'BIOI4440', name: 'Biological Data Analysis with R' },   
    { code: 'BIOI4464', name: 'Bioinformatics Methods' },
    { code: 'BIOI4270', name: 'Bioinformatics, Programming Course' },
    { code: 'BIOI4240', name: 'Structural Bioinformatics' },
    { code: 'BIOI4450', name: 'High Throughput Data Analysis' },     
    { code: 'BIOI4280', name: 'Algorithms in Bioinformatics' },      
    { code: 'BIOI4380', name: 'Bioinformatics Project' },
    { code: 'BIOI4463', name: 'Introduction to Genomics' },
    { code: 'BIOI2290', name: 'Mathematics for Bioinformatics' },
    { code: 'BIOI2291', name: 'Introduction to Biosciences' },
    { code: 'BIOI4303', name: 'Basic X - Ray Crystallography Techniques: How to Solve and Understand Protein Structures' },

    { code: 'KABI3001', name: 'Kasvifysiologian perusteet' },
    { code: 'KABI5070', name: 'Astrobiologian peruskurssi' },       
    { code: 'KABI5065', name: 'Elämän synty' },
    { code: 'KABI5073', name: 'Transcriptomics' },
    { code: 'KABI4004', name: 'Applied Photosynthesis Research' },
    { code: 'KABI4005', name: 'Microbial Metabolic Engineering' },
    { code: 'KABI4006', name: 'Plant Acclimation and Development' },
    { code: 'KABI4009', name: 'Fotosynteesin kirjatentti' },

    { code: 'BKEM5000', name: 'Avaimet biokemian opiskeluun' },
    { code: 'BKEM5030', name: 'Solu ja biomolekyylit - teoria' },
    { code: 'BKEM5031', name: 'Solu ja biomolekyylit - käytäntö' },
    { code: 'BKEM5010', name: 'Mikrobiologia - teoria' },
    { code: 'BKEM5011', name: 'Mikrobiologia - käytäntö' },
    { code: 'BKEM5020', name: 'Molekyylibiologia - teoria' },
    { code: 'BKEM5021', name: 'Molekyylibiologia - käytäntö' },
    { code: 'BKEM5160', name: 'Solu ja energia - teoria' },
    { code: 'BKEM5161', name: 'Solu ja energia - käytäntö' },
    { code: 'BKEM5140', name: 'Molekulaarinen kasvibiologia - teoria' },
    { code: 'BKEM5141', name: 'Molekulaarinen kasvibiologia - käytäntö' },
    { code: 'BKEM5151', name: 'Proteiinit ja entsyymit' },
    { code: 'BKEM5170', name: 'Elintarvikkeiden koostumus ja analytiikka - teoria' },
    { code: 'BKEM5171', name: 'Elintarvikkeiden koostumus ja analytiikka - käytäntö' },
    { code: 'BKEM5120', name: 'Immunologia - teoria' },
    { code: 'BKEM5121', name: 'Immunologia - käytäntö' },
    { code: 'BKEM5110', name: 'Biotekniikka 1' },
    { code: 'BKEM5111', name: 'Biotekniikka 2' },
    { code: 'BKEM5112', name: 'Biotekniikka 3' },
    { code: 'BKEM5113', name: 'Biotekniikka 4' },
    { code: 'BKEM1012', name: 'Bionanoscience' },
    { code: 'BKEM1050', name: 'In Silico Methodologies in Biochemistry and Molecular Medicine' },
    { code: 'BKEM5150', name: 'Proteiinit ja entsyymit - teoria' },
    { code: 'BKEM1051', name: 'Molecular Biology, Part 1' },
    { code: 'BKEM1052', name: 'Molecular Biology, Part 2' },
    { code: 'BKEM1053', name: 'Molecular Biology, Part 3' },
    { code: 'BKEM1054', name: 'Molecular Biology, Part 4' },
    { code: 'BKEM1060', name: 'Protein Structures and Structural Bioinformatics' },
    { code: 'BKEM1061', name: 'Protein Function at Cellular Level' },
    { code: 'BKEM1062', name: 'Enzyme and Protein Chemistry' },


    { code: 'BIOL1010', name: 'Ekologian perusteet' },
    { code: 'BIOL1101', name: 'Eliöiden rakenne' },
    { code: 'BIOL1111', name: 'Eliöiden tuntemuksen perusteet' },    
    { code: 'BIOL2091', name: 'Eliökunta' },
    { code: 'BIOL1201', name: 'Eläinfysiologian perusteet' },        
    { code: 'BIOL1301', name: 'Genetiikan perusteet' },
    { code: 'BIOL4060', name: 'Bioetiikka' },
    { code: 'BIOL3050', name: 'Bioinformatiikkaa biologeille' },     
    { code: 'BIOL2200', name: 'Biologian aineopintojen kirjatentti' },  
    { code: 'BIOL4051', name: 'Biologinen aineisto: johdatus tilastomenetelmiin' },
    { code: 'BIOL3011', name: 'Biologisen tutkimuksen perusteet' },
    { code: 'BIOL2100', name: 'Eliökunnan historia' },
    { code: 'BIOL2121', name: 'Evoluutiobiologia' },
    { code: 'BIOL2031', name: 'Kehitysbiologia ja evoluutio' },
    { code: 'BIOL4210', name: 'Biologinen aineisto: lineaariset mallit' },
    { code: 'BIOL4220', name: 'Biologinen aineisto: monimuuttujamenetelmät' },
    { code: 'BIOL4230', name: 'Biologinen aineisto: tilastosovelluksia R: llä' },
    { code: 'BIOL4310', name: 'Fenotyyppisen ja fylogeneettisen evoluution harjoitukset' },
    { code: 'BIOL2204', name: 'Selkärankaistutkimuksen käytännön taidot' },
    { code: 'BIOL4411', name: 'Advanced Conservation Biology' },
    { code: 'BIOL4321', name: 'Advanced Evolutionary Biology 1' },
    { code: 'BIOL4322', name: 'Advanced Evolutionary Biology 2' },
    { code: 'BIOL4300', name: 'Human Evolutionary Biology' },
    { code: 'BIOL4400', name: 'Marine and Coastal Environment' },
    { code: 'BIOL4600', name: 'Ympäristöbiologia' },
    { code: 'BIOL5050', name: 'Human Evolution' },
    { code: 'BIOL5320', name: 'Evolutionary Applications' },
    { code: 'BIOL5350', name: 'Molecular Systematics' },

    { code: 'FYGE2160', name: 'Ihmisen fysiologia' },
    { code: 'FYGE1010', name: 'Solubiologian luennot' },
    { code: 'FYGE4010', name: 'Ecotoxicology' },
    { code: 'FYGE2050', name: 'Ekofysiologia' },
    { code: 'FYGE1011', name: 'Fysiologian ja genetiikan aineopintojen kirjakuulustelu' },
    { code: 'FYGE2102', name: 'Genetiikan harjoitukset' },
    { code: 'FYGE1021', name: 'Genetiikan jatkoluennot' },
    { code: 'FYGE2252', name: 'Kromosomitutkimuksen harjoitukset' },
    { code: 'FYGE2251', name: 'Kromosomitutkimuksen luennot' },
    { code: 'FYGE2021', name: 'Mikroskooppitekniikat' },
    { code: 'FYGE2111', name: 'Neurobiologia' },
    { code: 'FYGE2041', name: 'Selkärankaisten anatomia, kehitysbiologia ja histologia' },
    { code: 'FYGE1020', name: 'Solubiologian harjoitukset' },
    { code: 'FYGE1024', name: 'Soluviljelytekniikat' },
    { code: 'FYGE2202', name: 'Transgeeniset geeniaktiivisuuksien tutkimusmenetelmät' },
    { code: 'FYGE4303', name: 'Literature in Physiology and Genetics 1' },
    { code: 'FYGE3160', name: 'Ihmisen genetiikka' },
    { code: 'FYGE4051', name: 'Eläinfysiologian menetelmäopinnot' },
    { code: 'FYGE4041', name: 'Solubiologian menetelmäopinnot' },
    { code: 'FYGE4021', name: 'Genetiikan menetelmäopinnot 1' },
    { code: 'FYGE4031', name: 'Genetiikan menetelmäopinnot 2' },
    { code: 'FYGE2060', name: 'Ekotoksikologian perusteet' },
    { code: 'FYGE5430', name: 'Next Generation Sequencing(NGS) and its Applications' },
    { code: 'FYGE2241', name: 'Mikrobien molekyyligenetiikka' },
    { code: 'FYGE5410', name: 'Recombination Mechanisms' },
    { code: 'FYGE5420', name: 'Immunologiset menetelmät genetiikassa' },
    { code: 'FYGE2242', name: 'Mikrobigenetiikan harjoitustyöt' },
    { code: 'FYGE4200', name: 'Eläinfysiologia' },
    { code: 'FYGE4400', name: 'Genetiikka' },
    { code: 'FYGE4400', name: 'Human Evolutionary Biology' },
    { code: 'FYGE4500', name: 'Solu- ja molekyylibiologia' },

    { code: 'XBIO4098', name: 'Eliöiden rakenne, toiminta ja perinnöllisyys' },
    { code: 'XBIO4129', name: 'Ekologian ja evoluutiobiologian perusteet' },   

    { code: 'BIOT2011', name: 'Ihmisen rakenne ja toiminta, Osa I' },
    { code: 'BIOT2012', name: 'Ihmisen rakenne ja toiminta, Osa II' },
    { code: 'BIOT2013', name: 'Ihmisen rakenne ja toiminta, Osa III' },
    { code: 'BIOT1502', name: 'Bioetiikka' },
    { code: 'BIOT1504', name: 'Biostatistiikka ja koesuunnittelu' },
    { code: 'BIOT1601', name: 'Biomateriaalitieteen perusteet' },
    { code: 'BIOT1520', name: 'Bioyrittäjyys 1' },
    { code: 'BIOT1521', name: 'Bioyrittäjyys 2' },
    { code: 'BIOT1518', name: 'Laatu ja metrologia' },
    { code: 'BIOT1508', name: 'Funktionaalinen genomiikka, proteomiikka ja bioinformatiikka' },
    { code: 'BIOT1501', name: 'Mikrobit ja ihminen, biolääketiede' },
    { code: 'BIOT1308', name: 'Syöpäbiologia' },
    { code: 'BIOT1519', name: 'Lääkemolekyylit ja proteiinien rakenteet' },
    { code: 'BIOT1515', name: 'Havainnoista päättelyyn' },
    { code: 'BIOT1517', name: 'Havainnoista päättelyyn syventävä osa' },
    { code: 'BIOT3009', name: 'Tekoäly diagnostiikan, lääkekehityksen ja kuvantamisen palveluksessa' },

    { code: 'FALL1014', name: 'Kemiallisen biologian perusteet' },
    { code: 'FALL1604', name: 'Johdatus orgaaniseen ja lääkeaineiden kemiaan' },
    { code: 'FALL1303', name: 'Neurobiologia' },
    { code: 'FALL3030', name: 'Farmakologia' },
    { code: 'FALL1012', name: 'Biofarmasia, farmakokinetiikka ja -genetiikka' },
    { code: 'FALL1606', name: 'Biomolekyylien ja lääkeaineiden kemia' },
    { code: 'FALL1705', name: 'Toksikologian ja riskinarvioinnin perusteet' },
    { code: 'FALL1703', name: 'Lääke-epidemiologia' },
    { code: 'FALL1011', name: 'Reseptorifarmakologia ja solumenetelmät lääkekehityksessä' },
    { code: 'FALL5518', name: 'Kokeellinen farmakologia' },
    { code: 'FALL0007', name: 'Kardiovaskulaarifarmakologia' },
    { code: 'FALL4006', name: 'Neuropsykiatristen häiriöiden biologinen tausta ja kohdespesifinen lääkehoito' },
    { code: 'FALL3030', name: 'Farmakologia' },
    { code: 'FALL5520', name: 'Farmakologia, lopputentti' },

    { code: 'BIMA2105', name: 'Biomedical Ethics' },


    { code: 'BIMA5101', name: 'Physical Basis of Medical Imaging' },
    { code: 'BIMA5103', name: 'Biomedical Instrumentation' },
    { code: 'BIMA5105', name: 'Fluorescence in Bioanalytical Research' },
    { code: 'BIMA3209', name: 'Bioimage Informatics 1' },
    { code: 'BIMA3211', name: 'Presenting Science by Means of Multimedia 1' },
    { code: 'BIMA3213',
    name: 'Nanoscopic Imaging in Biomedical Research' },
    { code: 'BIMA2105', name: 'Biomedical Ethics' },
    { code: 'BIMA3210', name: 'Bioimage Informatics 2' },
    { code: 'BIMA3216', name: 'Flow - cytometry Basics' },
    { code: 'BIMA3212', name: 'Presenting Science by Means of Multimedia 2' },
    { code: 'BIMA2104', name: 'Nanoscopic Imaging in Biomedical Research' },
    { code: 'BIMA3217', name: 'Hands - on Advanced optical microscopy' },
    { code: 'BIMA3218', name: 'Bioimage Informatics 1 – Basic Image Processing and Analysis' },
    { code: 'BIMA3219', name: 'Bioimage Informatics 2 – Image Processing and Analysis' },

    { code: 'DIBT0061', name: 'Immunomäärityksen kehittäminen' },
    { code: 'DIBT0062', name: 'Biotekniset järjestelmät' },
    { code: 'DIBT0058', name: 'Puhdastilatyöskentely' },

    { code: 'EKOL3129', name: 'Eliökunnan monimuotoisuus: eläinkunta' },
    { code: 'EKOL3139', name: 'Eliökunnan monimuotoisuus: kasvit, sienet ja levät' },
    { code: 'EKOL2109', name: 'Eliöyhteisö - ja ekosysteemiekologia' },
    { code: 'EKOL2353', name: 'Hyönteisten tuntemus' },
    { code: 'EKOL2356', name: 'Makrosienten lajintunnistus' },
    { code: 'EKOL2108', name: 'Populaatioekologia' },
    { code: 'EKOL2357', name: 'Punkkien tuntemus' },
    { code: 'EKOL2508', name: 'Puutarhakasvit' },
    { code: 'EKOL2359', name: 'Sammalten lajintuntemuksen perusteet' },
    { code: 'EKOL2352', name: 'Selkärangattomien tuntemus' },
    { code: 'EKOL2351', name: 'Selkärankaisten lajintuntemus' },
    { code: 'EKOL2348', name: 'Suomen hämähäkkieläimet' },
    { code: 'EKOL2322', name: 'Talviekologia' },
    { code: 'EKOL2412', name: 'Taksonomisen tutkimustyön peruskurssi' },
    { code: 'EKOL2302', name: 'Terrestrisen kasviekologian kenttäkurssi' },
    { code: 'EKOL2354', name: 'Kotimaisten putkilokasvien lajintuntemus' },
    { code: 'EKOL1011', name: 'Ekologian aineopintojen kirjakuulustelu' },
    { code: 'EKOL3030', name: 'Literature in Ecology and Evolutionary Biology 1' },
    { code: 'EKOL4101', name: 'Ecological Interactions' },
    { code: 'EKOL4320', name: 'Spatial Biodiversity Informatics and Landscape Ecology' },
    { code: 'EKOL4200', name: 'Biogeografia ja biodiversiteettitutkimus' },
    { code: 'EKOL4500', name: 'Taksonomia ja systematiikka' },
    { code: 'EKOL4100', name: 'Ekologian ja evoluutiobiologian syventävät opinnot' },
    { code: 'EKOL2311', name: 'Geographical Plant Ecology' },
    { code: 'EKOL3159', name: 'Introduction to R' },
    { code: 'EKOL2217', name: 'Tropical Ecology' },
    { code: 'EKOL4210', name: 'Biodiversity Research Course' },
    { code: 'EKOL2214', name: 'Evolution and Human Behaviour' },
    { code: 'EKOL4102', name: 'Environmental Ecology' },
    { code: 'EKOL4220', name: 'Literature in Ecology and Evolutionary Biology 2' },
    { code: 'EKOL2501', name: 'Riistabiologia' },

    { code: 'DEKE0001', name: 'Elintarvikekehityksen perusteet' },
    { code: 'DEKE0004', name: 'Kromatografinen analytiikka bioaloilla' },
    { code: 'DEKE0002', name: 'Elintarvikkeiden laatutekijät' },
    { code: 'DEKE0003', name: 'Elintarviketeknologia' },
    { code: 'DEKE0100', name: 'Food Development' },
    { code: 'DEKE0101', name: 'Functional Foods' },
    { code: 'DEKE0102', name: 'Food Product Safety' },
    { code: 'DEKE0103', name: 'Sensory Evaluation of Food' },
    { code: 'DEKE0106', name: 'Elintarviketurvallisuus ja - lainsäädäntö' },
    { code: 'DEKE0108', name: 'Applied Multivariate Methods in Food Sciences' },
    { code: 'DEKE0113', name: 'Final Exam in Food Development' },

    { code: 'FOOD3830', name: 'Elintarvikkeiden biokemia' },
    { code: 'FOOD3844', name: 'Elintarvikkeiden sekundaarimetaboliitit' },
    { code: 'FOOD3831', name: 'Elintarvikkeiden tuoteturvallisuus' },
    { code: 'FOOD8814', name: 'Massaspektrometrian sovelluksia elintarvikekemiassa' },
    { code: 'FOOD2107', name: 'Elintarvikekemian syventävien opintojen loppukuulustelu' },

    { code: 'FFYS6040', name: 'Aineen rakenneosat' },
    { code: 'FFYS6028', name: 'Fysiikan matemaattiset apuneuvot I' },
    { code: 'FFYS6029', name: 'Fysiikan matemaattiset apuneuvot II' },
    { code: 'FFYS6032', name: 'Kvanttimekaniikka IA' },
    { code: 'FFYS6014', name: 'Mekaniikka' },
    { code: 'FFYS6015', name: 'Optiikka' },
    { code: 'FFYS6024', name: 'Statistisen fysiikan perusteet' },
    { code: 'FFYS4294', name: 'Suhteellisuusteoria I' },
    { code: 'FFYS6034', name: 'Sähkö - ja magnetismioppi I' },
    { code: 'FFYS6025', name: 'Termodynamiikka' },
    { code: 'FFYS5000', name: 'Orientoivat opinnot(fysiikka)' },
    { code: 'FFYS5009', name: 'Fysiikka 1' },
    { code: 'FFYS5010', name: 'Fysiikka 2' },
    { code: 'FFYS5011', name: 'Fysiikka 3' },
    { code: 'FFYS5012', name: 'Fysiikka 4' },
    { code: 'FFYS6008', name: 'Fysiikan tietotekniset apuneuvot' },
    { code: 'FFYS6039', name: 'Aineen olomuodot ja ominaisuudet' },
    { code: 'FFYS7083', name: 'Nuclear and Particle Physics and Astrophysics' },
    { code: 'FFYS6031', name: 'Yeah, Science!' },
    { code: 'FFYS5004', name: 'Fysiikan peruskurssi 2' },
    { code: 'FFYS5003', name: 'Fysiikan peruskurssi 1' },
    { code: 'FFYS5005', name: 'Fysiikan peruskurssi 3' },
    { code: 'FFYS5006', name: 'Fysiikan peruskurssi 4' },
    { code: 'FFYS6019', name: 'Säteilyn käyttö ja turvallisuus' },
    { code: 'FFYS6000', name: 'Aineen mikro- ja nanorakenteen kuvantamismenetelmät' },
    { code: 'FFYS7072', name: 'Tutkimuksellinen ja kokeellinen fysiikan opetus' },
    { code: 'FFYS7066', name: 'Fysiikan ja kemian historia' },
    { code: 'FFYS1105', name: 'Fysiikan perusopinnot' },
    { code: 'FFYS7062', name: 'Simulaatiot fysiikan opetuksessa' },

    { code: 'FFYS7010', name: 'Applications of Fourier Transforms' },
    { code: 'FFYS7079', name: 'Magnetic Resonance Theory' },
    { code: 'FFYS7023', name: 'Molekyylien symmetria ja spektroskopia' },
    { code: 'FFYS7067', name: 'LabVIEW in Physical Applications' },
    { code: 'FFYS7014', name: 'Fysiikan mittausmenetelmät' },
    { code: 'FFYS7021', name: 'Materiaalitieteen karakterisointimenetelmät' },
    { code: 'FFYS7030', name: 'Röntgendiffraktiomenetelmien laboratoriokurssi' },
    { code: 'FFYS7031', name: 'Sähköstatiikka' },
    { code: 'FFYS7032', name: 'Säteilyn ja hiukkasten ilmaisimet' },
    { code: 'FFYS7068', name: 'Klassiset simulaatiomenetelmät fysiikassa' },
    { code: 'FFYS7086', name: 'Signal and Image Processing' },
    { code: 'FFYS7038', name: 'Syventävien opintojen kirjatentti' },
    { code: 'FFYS7015', name: 'Johdatus nanorakenteiden sovelluksiin' },
    { code: 'FFYS7012', name: 'Elektroni - ja ionispektroskopia' },
    { code: 'FFYS7016', name: 'Structural and thermal properties of solids' },
    { code: 'FFYS7077', name: 'Electrical Properties of Solids' },
    { code: 'FFYS7025', name: 'Pintatiede' },
    { code: 'FFYS7052', name: 'Fysiikan erikoiskurssi' },
    { code: 'FFYS7056', name: 'Introduction to Plasma Physics' },
    { code: 'FFYS7029', name: 'Puolijohteiden spektroskopia' },
    { code: 'FFYS7013', name: 'Experimental Methods in Condensed Matter Physics' },
    { code: 'FFYS7026', name: 'Point - contact Spectroscopy' },
    { code: 'FFYS6033', name: 'Quantum Mechanics IB' },
    { code: 'FFYS6035', name: 'Sähkö - ja magnetismioppi II' },
    { code: 'FFYS6036', name: 'Avaruusfysiikka' },
    { code: 'FFYS7055', name: 'Hydrodynamics and Hydromagnetics' },
    { code: 'FFYS7058', name: 'Plasma Astrophysics' },
    { code: 'FFYS7071', name: 'Space Missions and Instrumentation' },
    { code: 'FFYS7054', name: 'Heliophysics' },
    { code: 'FFYS7051', name: 'Special Course in Space Physics' },
    { code: 'FFYS7080', name: 'Magnetic Resonance Imaging' },
    { code: 'FFYS7073', name: 'Computational Materials Physics: Ab Initio Methods' },
    { code: 'FFYS7074', name: 'Computational Materials Physics: Modeling and Simulations' },
    { code: 'FFYS7075', name: 'Magnetism and Spintronics' },
    { code: 'FFYS7076', name: 'Electrical Transport in Solids and Interfaces' },
    { code: 'FFYS7078', name: 'Semiconductors' },
    { code: 'FFYS7081', name: 'FEM - mallinnus' },
    { code: 'FFYS7082', name: 'Molekyylien elektronirakenneteoria' },
    { code: 'FFYS7084', name: 'Magnetic Resonance Applications' },
    

    { code: 'GEOL1006', name: 'Mineraalit, kivilajit ja maaperäkerrostumat' },
    { code: 'GEOL1120', name: 'Skandinavian kvartäärikauden kehitys' },
    { code: 'GEOL1122', name: 'Metamorfinen petrologia ja metamorfiset kivet' },
    { code: 'GEOL1123', name: 'Rakennegeologia' },
    { code: 'GEOL4635', name: 'Pohjavesigeologia' },
    { code: 'GEOL1121', name: 'Geologiset tutkimusmenetelmät II' },
    { code: 'GEOL4560', name: 'Kallioperäkartoituksen peruskurssi' },
    { code: 'GEOL4524', name: 'Stratigrafinen tutkimus ja sen käytännöt' },
    { code: 'GEOL1125', name: '3D - mallinnuksen perusteet' },
    { code: 'GEOL1126', name: 'Magmapetrologian perusteet' },
    { code: 'GEOL1128', name: 'Yleinen kvartäärigeologia' },
    { code: 'GEOL1013', name: 'Geologiset luonnonvarat' },
    { code: 'GEOL1012', name: 'Geologiset prosessit' },
    { code: 'GEOL1134', name: 'Fennoskandian kallioperän kehitys' },
    { code: 'GEOL1200', name: 'Geologiset ilmastonmuutostutkimukset' },
    { code: 'GEOL1201', name: 'Kallioperägeologian kenttäkurssit' },
    { code: 'GEOL5000', name: 'Malmigeologia ja malminetsintä' },

    { code: 'GMIN4800', name: 'Kallioperägeologia I' },
    { code: 'GMIN4818', name: 'Metamorphic Processes' },
    { code: 'GMIN4819', name: 'Global Tectonics' },
    { code: 'GMIN4900', name: 'Kallioperägeologia II' },
    { code: 'GMIN5000', name: 'Soveltava rakennegeologia' },

    { code: 'KEMI6128', name: 'Katalyytti - Kemian orientoivat opinnot I' },
    { code: 'KEMI6129', name: 'Aktivaattori - Kemian orientoivat opinnot II' },
    { code: 'KEMI6004', name: 'Kemian perusopinnot' },
    { code: 'KEMI6101', name: 'Kemia I' },
    { code: 'KEMI6102', name: 'Kemia II' },
    { code: 'KEMI6103', name: 'Kemia III' },
    { code: 'KEMI6104', name: 'Kemia IV' },
    { code: 'KEMI6107', name: 'Analyyttinen kemia' },
    { code: 'KEMI6108', name: 'Epäorgaaninen kemia' },
    { code: 'KEMI6109', name: 'Fysikaalinen kemia I' },
    { code: 'KEMI6110', name: 'Orgaaninen kemia' },
    { code: 'KEMI6115', name: 'Fysikaalinen kemia II' },
    { code: 'KEMI6116', name: 'Kemiallinen biologia' },
    { code: 'KEMI6117', name: 'Laskennallinen kemia ja molekyylimallinnus' },
    { code: 'KEMI6118', name: 'Luonnonyhdisteiden kemia' },
    { code: 'KEMI6119', name: 'Materiaalikemia ja nanoteknologia' },
    { code: 'KEMI6120', name: 'Siirtymämetallien bioepäorgaaninen kemia' },
    { code: 'KEMI6121', name: 'Spektroskopian perusteet' },
    { code: 'KEMI6122', name: 'Ympäristökemia' },
    { code: 'KEMI6301', name: 'Kemian peruskurssi I' },
    { code: 'KEMI6302', name: 'Kemian peruskurssi II' },
    { code: 'KEMI6131', name: 'Kemistin PC-perusohjelmat' },
    { code: 'KEMI6401', name: 'Structure and Reactivity I' },
    { code: 'KEMI6402', name: 'Structure and Reactivity II' },
    { code: 'KEMI6409', name: 'LC-MS and its Applications' },
    { code: 'KEMI6427', name: 'Structure, Activity and Quantitation Methods' },
    { code: 'KEMI6403', name: 'Bioorganic Chemistry' },
    { code: 'KEMI6406', name: 'Medicinal Chemistry' },
    { code: 'KEMI6405', name: 'Organic Synthesis' },
    { code: 'KEMI6404', name: 'Physical Organic Chemistry' },
    { code: 'KEMI6424', name: 'Fundamentals of Radiochemistry' },
    { code: 'KEMI6426', name: 'Measuring Techniques in Radiochemistry' },
    { code: 'KEMI6425', name: 'Chemistry of Positron Emitting Radiodrugs' },
    { code: 'KEMI6428', name: 'Radiosynthetic Techniques' },
    { code: 'KEMI6429', name: 'Natural compound chemistry' },
    { code: 'KEMI6416', name: 'Screening of Plants for Bioactivity and Bioactive Compounds' },
    { code: 'KEMI6414', name: 'Chemistry of Tannins and Other Polyphenols' },
    { code: 'KEMI6430', name: 'Identification of Bioactives by UV, MS and MS/MS Spectra' },
    { code: 'KEMI6504', name: 'Chemistry of Metals' },
    { code: 'KEMI6513', name: 'Functional Materials' },
    { code: 'KEMI6505', name: 'Quantum Mechanics and Molecular Symmetry' },
    { code: 'KEMI6506', name: 'Molecules and Statistics' },
    { code: 'KEMI6507', name: 'Surfaces and Materials' },
    { code: 'KEMI6508', name: 'Dynamics and Change' },
    { code: 'KEMI6501', name: 'Molecular Spectroscopy' },
    { code: 'KEMI6510', name: 'X - ray Analysis in Materials Chemistry' },
    { code: 'KEMI6502', name: 'Syntheses in Materials Chemistry' },
    { code: 'KEMI6511', name: 'Luminescence in solid materials' },
    { code: 'KEMI6503', name: 'Metal - organic Chemistry and Catalysis' },
    { code: 'KEMI6512', name: 'Experimental Techniques for Materials Characterization' },
    { code: 'KEMI6519', name: 'Applied FTIR and Raman Spectroscopy' },
    { code: 'KEMI6509', name: 'Thermal analysis in materials chemistry' },
    { code: 'KEMI6520', name: 'Applied Luminescence' },
    { code: 'KEMI6521', name: 'Analytical Separation Techniques' },
    { code: 'KEMI6208', name: 'Fysiikan ja kemian historia' },
    { code: 'KEMI4025', name: 'Characterization of Energy Materials' },

    { code: 'MAAN6080', name: 'Geoinformatiikan perusteet' },
    { code: 'MAAN6151', name: 'Geomorfologia' },
    { code: 'MAAN6732', name: 'Paikkatietomenetelmät' },
    { code: 'MAAN6154', name: 'Biogeografia' },
    { code: 'MAAN6091', name: 'Johdatus maantieteeseen' },
    { code: 'MAAN6043', name: 'Aluemaantieteen perusteet' },
    { code: 'MAAN6055', name: 'Luonnonvarojen maantiede' },
    { code: 'MAAN6691', name: 'Maantieteen tutkimustaitojen perusteet' },
    { code: 'MAAN6152', name: 'Hydrogeografia' },
    { code: 'MAAN6153', name: 'Klimatologia' },
    { code: 'MAAN6230', name: 'Kaupunkimaantiede' },
    { code: 'MAAN6260', name: 'Yhteiskunta- ja poliittinen maantiede' },
    { code: 'MAAN6262', name: 'Talousmaantiede' },
    { code: 'MAAN6258', name: 'Aluekehitys ja innovaatioiden maantiede' },
    { code: 'MAAN6302', name: 'Teoria, metodologia ja alueet maantieteessä' },
    { code: 'MAAN6682', name: 'Kehitysmaantiede' },
    { code: 'MAAN6734', name: 'Kaukokartoitusmenetelmät' },
    { code: 'MAAN7551', name: 'Aluekehitys, -suunnittelu ja - politiikka' },
    { code: 'MAAN7501', name: 'Development and Geography' },
    { code: 'MAAN7363', name: 'Fluvial and Coastal Environments' },
    { code: 'MAAN7365', name: 'Fluvial and Coastal Fieldwork Course' },
    { code: 'MAAN7663', name: 'GIS and Society' },
    { code: 'MAAN7560', name: 'Geography of Knowledge Creation and Innovations' },
    { code: 'MAAN7354', name: 'Global Change' },
    { code: 'MAAN7340', name: 'Participation, Spatial Planning and GIS' },
    { code: 'MAAN7563', name: 'Legal Geography' },
    { code: 'MAAN7315', name: 'Marine and Coastal Spatial Planning' },
    { code: 'MAAN7504', name: 'Merenkulun kuljetuslogistiikka ja talousmaantiede' },
    { code: 'MAAN7364', name: 'Practicals in Fluvial and Coastal Environments' },
    { code: 'MAAN7842', name: 'Urbaani turvallisuuspolitiikka' },
    { code: 'MAAN7344', name: 'Applied Biogeography' },
    { code: 'MAAN7761', name: 'Applied Geospatial Methods' },
    { code: 'MAAN7762', name: 'Remote Sensing of Environment' },
    { code: 'MAAN7764', name: 'Geospatial Data Management and Visualization' },
    { code: 'MAAN7711', name: 'Urban Development and Place Promotion' },
    { code: 'MAAN7003', name: 'Autokorrelaatio' },
    { code: 'MAAN7345', name: 'LiDAR -Based Approach on Glacial Landscapes' },
    { code: 'MAAN7004', name: 'Introduction to the Water Energy Food Nexus (WEFN)' },

    { code: 'MATE5019', name: 'Analyysi I' },
    { code: 'MATE5351', name: 'Analyysi IIA' },
    { code: 'MATE5216', name: 'Lineaarialgebra' },
    { code: 'MATE5060', name: 'Algebran peruskurssi I' },
    { code: 'MATE5352', name: 'Analyysi IIB' },
    { code: 'MATE5059', name: 'Geometria' },
    { code: 'MATE5172', name: 'Matematiikan historia' },
    { code: 'MATE5357', name: 'Matematiikan peruskurssi 1' },
    { code: 'MATE5358', name: 'Matematiikan peruskurssi 2' },
    { code: 'MATE5361', name: 'Johdatus lineaarialgebraan' },
    { code: 'MATE5015', name: 'Analyysi I(sivuaineopiskelijoille)' },
    { code: 'MATE5018', name: 'Analyysi II(sivuaineopiskelijoille)' },
    { code: 'MATE5043', name: 'Lineaarialgebra(sivuaineopiskelijoille)' },
    { code: 'MATE5398', name: 'Insinöörimatematiikka A' },
    { code: 'MATE5399', name: 'Insinöörimatematiikka B' },
    { code: 'MATE5400', name: 'Insinöörimatematiikka C' },
    { code: 'MATE5401', name: 'Insinöörimatematiikka D' },
    { code: 'MATE5353', name: 'Johdatus automaattien teoriaan' },
    { code: 'MATE6015', name: 'Abstraktin matematiikan pohjatietokurssi' },
    { code: 'MATE5287', name: 'Matematiikan opiskelumenetelmät I' },
    { code: 'MATE5288', name: 'Matematiikan opiskelumenetelmät II' },
    { code: 'MATE5341', name: 'Foundations of Cryptography' },
    { code: 'MATE5396', name: 'Cryptography I' },
    { code: 'MATE5397', name: 'Cryptography II' },
    { code: 'MATE5344', name: 'Algebraic Structures in Cryptography' },
    { code: 'MATE5345', name: 'Selected Topics in Cryptography' },
    { code: 'MATE5061', name: 'Algebran peruskurssi II' },
    { code: 'MATE5074', name: 'Algoritminen matematiikka' },
    { code: 'MATE5045', name: 'Differentiaaliyhtälöt' },
    { code: 'MATE5039', name: 'Kombinatoriikka' },
    { code: 'MATE5354', name: 'Lebesguen mitta ja integraali' },
    { code: 'MATE5114', name: 'Logiikka' },
    { code: 'MATE5359', name: 'Matematiikan peruskurssi 3' },
    { code: 'MATE5360', name: 'Matematiikan peruskurssi 4' },
    { code: 'MATE5356', name: 'Vektorilaskenta' },
    { code: 'MATE5355', name: 'Tieteellinen laskenta' },
    { code: 'MATE5123', name: 'Lukuteoria' },
    { code: 'MATE5290', name: 'Algorithmic Complexity' },
    { code: 'MATE5225', name: 'Automata and Formal Languages' },
    { code: 'MATE5207', name: 'Pro gradu -tutkielma matematiikassa, aineenopettajat' },
    { code: 'MATE5418', name: 'Analyyttinen geometria' },
    { code: 'MATE5414', name: 'Ohjelmointi matematiikan opetuksessa(opettajille)' },
    { code: 'MATE6017', name: 'Reaalianalyysi 1' },
    { code: 'MATE6018', name: 'Reaalianalyysi 2' },
    { code: 'MATE5417', name: 'Topics in Analysis' },
    { code: 'MATE5313', name: 'Koodausteoria I' },
    { code: 'MATE5324', name: 'Koodausteoria II' },
    { code: 'MATE5230', name: 'Graph Theory' },
    { code: 'MATE5161', name: 'Kombinatoriikan jatkokurssi' },
    { code: 'MATE5038', name: 'Combinatorial Enumeration' },
    { code: 'MATE5085', name: 'Convolutional Codes' },
    { code: 'MATE5316', name: 'Äärelliset kunnat' },
    { code: 'MATE5148', name: 'Tilings and Patterns' },
    { code: 'MATE5305', name: 'Cellular Automata' },
    { code: 'MATE5411', name: 'Symbolic Dynamics' },
    { code: 'MATE5075', name: 'Combinatorics on Words' },
    { code: 'MATE5175', name: 'Puoliryhmät' },
    { code: 'MATE5096', name: 'Logiikan jatkokurssi' },
    { code: 'MATE5416', name: 'Set Theory' },
    { code: 'MATE5362', name: 'Funktioteoria' },
    { code: 'MATE5125', name: 'Ryhmäteoria' },
    { code: 'MATE5055', name: 'Algebra' },
    { code: 'MATE5208', name: 'Lukuteorian jatkokurssi' },
    { code: 'MATE5095', name: 'Analyyttinen lukuteoria' },
    { code: 'MATE5413', name: 'p - adiset luvut' },
    { code: 'MATE5182', name: 'Lien algebrat ja niiden esitysteoria' },
    { code: 'MATE6025', name: 'Selected Topics in Analysis' },
    { code: 'MATE5325', name: 'Topologian perusteet' },
    { code: 'MATE5124', name: 'Matriisilaskenta' },
    { code: 'MATE6020', name: 'Advanced Symbolic Dynamics' },
    { code: 'MATE6021', name: 'Combinatorial Structures' },
    { code: 'MATE6022', name: 'Diskreetin matematiikan erikoiskurssi I' },
    { code: 'MATE6023', name: 'Diskreetin matematiikan erikoiskurssi II' },
    { code: 'MATE6024', name: 'Matemaattinen ongelmanratkaisu ja ohjelmointi(opettajille)' },
    { code: 'MATE5422', name: 'Computational Modeling: Methods and Applications' },
    { code: 'MATE5423', name: 'Introduction to Computational and Systems Biology' },
    { code: 'MATE5424', name: 'Foundations of Machine Learning' },

    { code: 'SMAT5108', name: 'Matemaattinen optimointi I' },
    { code: 'SMAT5109', name: 'Matemaattinen optimointi II' },
    { code: 'SMAT5176', name: 'Numeerinen analyysi' },
    { code: 'SMAT5306', name: 'Todennäköisyyslaskennan jatkokurssi' },
    { code: 'SMAT5045', name: 'Differentiaaliyhtälöt' },
    { code: 'SMAT5116', name: 'Numeerinen analyysi(opettajille)' },
    { code: 'SMAT5035', name: 'Partial Differential Equations' },
    { code: 'SMAT5016', name: 'Konveksi analyysi ja optimointi' },
    { code: 'SMAT5309', name: 'Epäsileä analyysi' },
    { code: 'SMAT5215', name: 'Matemaattinen mallintaminen' },
    { code: 'SMAT5129', name: 'Riskiteoria' },
    { code: 'SMAT5322', name: 'Dynaamisen peliteorian jatkokurssi' },
    { code: 'SMAT5321', name: 'Dynaaminen peliteoria' },
    { code: 'SMAT5313', name: 'Stokastinen integrointi' },
    { code: 'SMAT5037', name: 'Optimointialgoritmit' },
    { code: 'SMAT5312', name: 'Stokastinen optimointi' },
    { code: 'SMAT5023', name: 'Stokastiset prosessit' },
    { code: 'SMAT5058', name: 'Sekalukuoptimointi' },
    { code: 'SMAT5310', name: 'Epäsileä optimointi' },
    { code: 'SMAT5218', name: 'Robust Optimization' },
    { code: 'SMAT5150', name: 'Combinatorial Optimization Algorithms' },
    { code: 'SMAT5302', name: 'Operations Research with Applications' },
    { code: 'SMAT5059', name: 'Vector Optimization' },
    { code: 'SMAT5308', name: 'Calculus of Variations' },
    { code: 'SMAT5307', name: 'Control Theory' },
    { code: 'SMAT5151', name: 'Scheduling Theory' },
    { code: 'SMAT5217', name: 'Game Theory' },
    { code: 'SMAT5219', name: 'Heuristics' },
    { code: 'SMAT5301', name: 'Simulation' },
    { code: 'SMAT5314', name: 'Optimoinnin erikoiskurssi' },
    { code: 'SMAT5315', name: 'Sovelletun matematiikan erikoiskurssi I' },
    { code: 'SMAT5316', name: 'Sovelletun matematiikan erikoiskurssi II' },
    { code: 'SMAT5317', name: 'Henkivakuutusmatematiikka' },
    { code: 'SMAT5318', name: 'Vakuutusmatematiikan erikoiskurssi' },
    { code: 'SMAT5319', name: 'Todennäköisyysteoria' },
    { code: 'SMAT5320', name: 'Stokastiikan erikoiskurssi' },
    { code: 'SMAT5324', name: 'Cluster Analysis via Nonsmooth Optimization' },

    { code: 'TFYS6011', name: 'Differentiaaligeometria' },
    { code: 'TFYS6008', name: 'Kvanttikokeet' },
    { code: 'TFYS6012', name: 'Kvanttimekaniikka IIA' },
    { code: 'TFYS6009', name: 'Suhteellisuusteoria II' },
    { code: 'TFYS6010', name: 'Sähködynamiikka' },
    { code: 'TFYS7024', name: 'Presentation Skills' },
    { code: 'TFYS7027', name: 'Hilbertin avaruuden operaattorit' },
    { code: 'TFYS7028', name: 'Open Quantum Systems 1' },
    { code: 'TFYS7029', name: 'Open Quantum Systems 2' },
    { code: 'TFYS7030', name: 'Quantum Field Theory 1' },
    { code: 'TFYS7031', name: 'Quantum Field Theory 2' },
    { code: 'TFYS7032', name: 'Statistical Physics 1' },
    { code: 'TFYS7033', name: 'Statistical Physics 2' },
    { code: 'TFYS7034', name: 'Cosmology 1' },
    { code: 'TFYS7035', name: 'Cosmology 2' },
    { code: 'TFYS7036', name: 'Differentiaaligeometrian jatkokurssi' },
    { code: 'TFYS7025', name: 'Network Theory' },
    { code: 'TFYS7038', name: 'Quantum Optics' },
    { code: 'TFYS7039', name: 'Quantum Information' },
    { code: 'TFYS6013', name: 'Kvanttimekaniikka IIB' },

    { code: 'TKO_3103', name: 'Data Analysis and Knowledge Discovery' },
    { code: 'TKO_3104', name: 'Data ja vuorovaikutus' },
    { code: 'TKO_5736', name: 'Tietojenkäsittelyn perusteet I' },
    { code: 'TKO_2038', name: 'Algoritmien ja ohjelmoinnin peruskurssi' },
    { code: 'TKO_2005', name: 'Olio - ohjelmoinnin perusteet' },
    { code: 'TKO_3122', name: 'Tietokantojen perusteet 1' },
    { code: 'TKO_5735', name: 'Tietokantojen perusteet 2' },
    { code: 'TKO_5738', name: 'Tietojenkäsittelyn perusteet II' },
    { code: 'TKO_3107', name: 'Tietorakenteet ja algoritmit' },
    { code: 'TKO_2086', name: 'Bioinformatiikan perusteet' },
    { code: 'TKO_8966', name: 'Johdatus kieliteknologiaan' },
    { code: 'TKO_3110', name: 'Principles of Interaction Design' },
    { code: 'TKO_3108', name: 'Algorithm Design' },
    { code: 'TKO_2096', name: 'Applications of Data Analysis' },
    { code: 'TKO_3120', name: 'Machine Learning and Pattern Recognition' },
    { code: 'TKO_3109', name: 'Advanced Algorithm Design' },
    { code: 'TKO_3121', name: 'Machine Learning and Algorithmics Seminar' },
    { code: 'TKO_3113', name: 'Educational Technology and Technology Education' },
    { code: 'TKO_2081', name: 'Introduction to Game Development Tools' },
    { code: 'TKO_3118', name: 'IxD Seminar' },
    { code: 'TKO_3125', name: 'Practical Course in Digital Educational Technologies' },
    { code: 'TKO_3115', name: 'Learning Analytics' },
    { code: 'TKO_3112', name: 'Game Design' },
    { code: 'TKO_2029', name: 'Interactive Storytelling' },
    { code: 'TKO_3119', name: 'Inclusive Innovation in the Global South' },
    { code: 'TKO_5710', name: 'Algorithms for Computer Games' },
    { code: 'TKO_5725', name: 'Multiplayer Computer Games' },
    { code: 'TKO_3177', name: 'Orientoivat opinnot' },
    { code: 'TKO_2103', name: 'Johdatus tekoälyyn' },
    { code: 'TKO_3128', name: 'Tekoälyn perusmenetelmät' },
    { code: 'TKO_5737', name: 'Tietojenkäsittelyn perusteet I, tentti' },
    { code: 'TKO_8612', name: 'Deep Learning' },
    { code: 'TKO_8963', name: 'Search Engines and Document Retrieval Methods' },
    { code: 'TKO_8964', name: 'Textual Data Analysis' },
    { code: 'TKO_8965', name: 'Deep Learning in Human Language Technology' },
    { code: 'TKO_8960', name: 'Mixed Reality' },
    { code: 'TKO_8967', name: 'Research Methods and Tools' },
    { code: 'TKO_3127', name: 'Game Testing' },
    { code: 'TKO_5739', name: 'Digital Art Master Class' },
    { code: 'TKO_8969', name: 'Gamification and Serious Games' },

    { code: 'DTEK1050', name: 'Tietoverkkotekniikat' },
    { code: 'DTEK1048', name: 'Olio - ohjelmoinnin metodiikka' },
    { code: 'DTEK1201', name: 'Ohjelmistotuotannon peruskurssi' },
    { code: 'DTEK1049', name: 'Käyttöliittymät' },
    { code: 'DTEK1064', name: 'Tietoyhteiskunta ja kyberturvallisuus' },
    { code: 'DTEK1066', name: 'Hajautetut ohjelmistojärjestelmät ja pilvipalvelut' },
    { code: 'DTEK1046', name: 'Ohjelmointikielet ja - paradigmat' },
    { code: 'DTEK0044', name: 'Project Management' },
    { code: 'DTEK1051', name: 'Tietokonearkkitehtuurit ja käyttöjärjestelmät' },
    { code: 'DTEK8025', name: 'System and Application Security' },
    { code: 'DTEK1075', name: 'Health Informatics' },
    { code: 'DTEK8080', name: 'Medical Instrumentation' },
    { code: 'DTEK0042', name: 'Acquisition and Analysis of Biosignals' },
    { code: 'DTEK8095', name: 'DSP System Engineering' },
    { code: 'DTEK8081', name: 'Embedded IoT Programming' },
    { code: 'DTEK0043', name: 'IoT Systems: Design and Applications' },
    { code: 'DTEK8097', name: 'Secure Sensor Network Systems' },
    { code: 'DTEK8099', name: 'Practical Software Quality Management, Testing and Estimation' },
    { code: 'DTEK1045', name: 'Insinöörityön perusteet' },
    { code: 'DTEK1043', name: 'Opiskelun ja työelämän tietotekniikka' },
    { code: 'DTEK1203', name: 'Mikroprosessorit' },
    { code: 'DTEK1039', name: 'Tiedonsiirron perusteet' },
    { code: 'DTEK1205', name: 'Lineaariset järjestelmät ja piirit' },
    { code: 'DTEK1019', name: 'Sulautetut prosessorijärjestelmät' },
    { code: 'DTEK1206', name: 'Elektroniikkajärjestelmät' },
    { code: 'DTEK1207', name: 'Digitaaliset tietoliikennejärjestelmät' },
    { code: 'DTEK1208', name: 'Digitaalinen signaalinkäsittely' },
    { code: 'DTEK8098', name: 'Software Development and Software Security' },
    { code: 'DTEK8100', name: 'Lean Platforms' },
    { code: 'DTEK8067', name: 'HDL Based Design' },
    { code: 'DTEK1057', name: 'Energy Efficient Embedded Electronics' },
    { code: 'DTEK8082', name: 'FPGA Prototyping and Configurable Computing' },
    { code: 'DTEK2026', name: 'System Verification' },
    { code: 'DTEK2027', name: 'Multiprocessor Architectures' },
    { code: 'DTEK8060', name: 'Protocol Processing and Security' },
    { code: 'DTEK8096', name: 'Network Infrastructure Technologies and Security' },
    { code: 'DTEK2029', name: 'Human Element in Information Security' },
    { code: 'DTEK0039', name: 'Security Engineering' },
    { code: 'DTEK2030', name: 'Reconfigurable Computing' },
    { code: 'DTEK1074', name: 'Introduction to Health and Wellbeing Technologies' },
    { code: 'DTEK0046', name: 'Technological Systems, Foresight and Societal Change' },
    { code: 'DTEK1072', name: 'Technology Leadership' },
    { code: 'DTEK0048', name: 'Product Development and Management - PDM' },
    { code: 'DTEK2023', name: 'International Exchange Experience' },
    { code: 'DTEK0106', name: 'Insinöörityöskentely T & K ympäristössä' },
    { code: 'DTEK0045', name: 'Internship' },
    { code: 'DTEK0037', name: 'Seminar on Embedded Computing' },
    { code: 'DTEK2012', name: 'Advanced Sensor Networking' },
    { code: 'DTEK8063', name: 'Firewall and IPS Technology' },
    { code: 'DTEK1067', name: 'Opiskelun ja työelämän tietotekniikka, Digitaalisuus' },
    { code: 'DTEK1068', name: 'Opiskelun ja työelämän tietotekniikka, Tieto - ja kyberturvallisuus' },
    { code: 'DTEK1069', name: 'Opiskelun ja työelämän tietotekniikka, Toimistosovellukset' },
    { code: 'DTEK1070', name: 'Opiskelun ja työelämän tietotekniikka, Unix' },
    { code: 'DTEK2034', name: 'Communication Technologies and Security in IoT' },
    { code: 'DTEK2037', name: 'Lean Platform Business Design' },
    { code: 'DTEK2038', name: 'Co - Creation and New Product Development' },
    { code: 'DTEK2039', name: 'Technological phenomena in context' },
    { code: 'DTEK2040', name: 'Web - ja mobiiliohjelmointi' },
    { code: 'DTEK1076', name: 'Opiskelun ja työelämän tietotekniikka, Matlab' },
    { code: 'DTEK2041', name: 'Sulautettujen järjestelmien ohjelmointi' },
    { code: 'DTEK8083', name: 'Digital Systems Engineering' },
    { code: 'DTEK8084', name: 'Smart Systems Applications' },
    { code: 'DTEK8085', name: 'Autonomous Systems Architectures' },
    { code: 'DTEK8086', name: 'Sensors and Interfaces' },
    { code: 'DTEK8087', name: 'Design Methods for Embedded Systems' },
    { code: 'DTEK8091', name: 'Co - creation and Platform Economy' },
    { code: 'DTEK8092', name: 'Industrial ICT' },
    { code: 'DTEK8101', name: 'Advanced Programming Techniques' },
    { code: 'DTEK8102', name: 'Privacy and Security for Software Systems' },
    { code: 'DTEK8103', name: 'Software Design and Architecture' },
    { code: 'DTEK8104', name: 'Software Engineering Seminar' },
    { code: 'DTEK8105', name: 'Software House' },
    { code: 'DTEK8088', name: 'Analog IC Design' },
    { code: 'DTEK8089', name: 'Mixed-Mode IC Design' },
    { code: 'DTEK8090', name: 'RF IC Design' },
    { code: 'DTEK1044', name: 'Teollisuustalouden ja tuote- ja palveluliiketoiminnan opintojakso' },
    { code: 'DTEK8106', name: 'Digital Standard Cell Integration' },
    { code: 'DTEK8107', name: 'Mismatch in IC Design' },
    { code: 'DTEK8092', name: 'Industrial ICT' },
    { code: 'DTEK8091', name: 'Co-creation and Platform Economy' },
    { code: 'DTEK8110', name: 'Engineering Profession' },
    { code: 'DTEK8108', name: 'Työelämätaidot ja palvelukulttuuri sote:ssa' },
    { code: 'DTEK8109', name: 'Digitalisaatio sote-palveluissa' },
    { code: 'DTEK8111', name: 'Digitalisaatio sosiaali- ja terveydenhuollon palveluissa' },
    { code: 'DTEK1078', name: 'Tietoturva ja tietosuoja tekoälysovelluksissa' },

    { code: 'TILM3555', name: 'Tilastollisen päättelyn peruskurssi' },
    { code: 'TILM3553', name: 'Todennäköisyyslaskennan peruskurssi' },
    { code: 'TILM3517', name: 'Basics of R - Language' },
    { code: 'TILM3568', name: 'Todennäköisyyslaskenta sivuaineopiskelijoille' },
    { code: 'TILM3525', name: 'Tilastotieteen peruskurssi soveltajille' },
    { code: 'TILM3556', name: 'Aineiston hankinta ja tutkimusasetelmat' },
    { code: 'TILM3557', name: 'Tilastollisten mallien peruskurssi' },
    { code: 'TILM3517', name: 'R-kielen alkeet' },
    { code: 'TILM3561', name: 'Tilastollinen päättely I' },
    { code: 'TILM3562', name: 'Tilastollinen päättely II' },
    { code: 'TILM3588', name: 'Lineaariset ja yleistetyt lineaariset mallit' },
    { code: 'TILM3524', name: 'SAS-kurssi' },
    { code: 'TILM3580', name: 'Tilastollinen ohjelmointi' },
    { code: 'TILM3520', name: 'Yleistetyt lineaariset mallit' },
    { code: 'TILM3559', name: 'LuK-tutkielma (tilastotiede)' },
    { code: 'TILM3541', name: 'Aikasarja-analyysi' },
    { code: 'TILM3543', name: 'Elinaika-analyysi' },
    { code: 'TILM3578', name: 'Epidemiologian tilastolliset menetelmät' },
    { code: 'TILM3540', name: 'Introduction to Multivariate Methods' },
    { code: 'TILM3529', name: 'Kausaalipäättely havainnoivissa tutkimuksissa' },
    { code: 'TILM3579', name: 'Kokeiden suunnittelu ja analyysi' },
    { code: 'TILM3574', name: 'Matriisilaskenta tilastotieteessä' },
    { code: 'TILM3545', name: 'Monimuuttujamenetelmien teoria' },
    { code: 'TILM3542', name: 'Tilastollinen konsultaatio' },
    { code: 'TILM3581', name: 'Financial and Time Series Econometrics' },
    { code: 'TILM3522', name: 'Graduseminaari tilastotieteessä' },
    { code: 'TILM3527', name: 'Hierarkkinen mallintaminen' },
    { code: 'TILM3546', name: 'Pitkittäisaineistojen analyysi' },
    { code: 'TILM3519', name: 'Tilastollisen päättelyn teoria' },
    { code: 'TILM3521', name: 'Laskennallinen tilastotiede' },
    { code: 'TILM3577', name: 'Bayes - päättely' },
    { code: 'TILM3585', name: 'GLMM - mallit SAS - ohjelmistolla' },
    { code: 'TILM3530', name: 'Kliiniset kokeet' },
    { code: 'TILM3586', name: 'Moniulotteinen aikasarja - analyysi' },
    { code: 'TILM3547', name: 'Rakenneyhtälömallit' },
    { code: 'TILM3587', name: 'Regressioanalyysi ja tilastollinen oppiminen' },
    { code: 'TILM3539', name: 'Tilastotieteen peruskurssi soveltajille(hoitotiede)' },
    { code: 'TILM3589', name: 'Epälineaarinen aikasarja - analyysi' },
    { code: 'TILM3590', name: 'Tapahtumahistoriamallit' },
    { code: 'TILM3582', name: 'Tilastotieteen perusteet' },
    { code: 'TILM3583', name: 'Tilastollisten mallien perusteet' },
    { code: 'TILM3591', name: 'R Course for Researchers' },
    { code: 'TILM3592', name: 'Tilastollisen oppimisen jatkokurssi' },
    { code: 'TILM3564', name: 'Tilastotieteen peruskurssi soveltajille (maantiede)' },
    { code: 'TILM3593', name: 'Tilastotieteen peruskurssi soveltajille (Biokemia)' },
    { code: 'TILM3594', name: 'Intensive Course in Statistics' },
    { code: 'TILM3595', name: 'Diskreetin aineiston analyysi' },

    { code: 'YMPS6050', name: 'Ympäristötieteen loppukuulustelu I' },
    { code: 'YMPS6051', name: 'Ympäristötieteen loppukuulustelu II' },
    { code: 'YMPS1016', name: 'Maisemaekologia' },
    { code: 'YMPS6045', name: 'Kansainvälinen talous ja ympäristöongelmat' },
    { code: 'YMPS6013', name: 'Ympäristönsuojeluoikeuden yleinen osa' },
    { code: 'YMPS6014', name: 'Ympäristönsuojeluoikeuden erityinen osa' },
    { code: 'YMPS1040', name: 'Luonnon - ja ympäristönsuojelun historia' },
    { code: 'YMPS6043', name: 'Conservation Biology' },
    { code: 'YMPS6002', name: 'Environment and Development' },
    { code: 'YMPS1006', name: 'Maailmanlaajuiset ympäristöongelmat' },
    { code: 'YMPS1051', name: 'Ympäristön kemikalisoituminen ja päästöjen hallinta' },
    { code: 'YMPS1052', name: 'Ympäristö ja yhteiskunta' },
    { code: 'YMPS1009', name: 'Ympäristöekologia ja luonnonsuojelu' },
    { code: 'YMPS4842', name: 'Ihminen ja kulttuuriympäristö' },
    { code: 'YMPS6004', name: 'Ympäristöoikeuden perusteet' },
    { code: 'YMPS6008', name: 'Ympäristötalous' },
    { code: 'YMPS1054', name: 'Ympäristötiedon haku ja hallinta' },
    { code: 'YMPS6018', name: 'Itämeren ympäristön tila ja tulevaisuus' },
    { code: 'YMPS3011', name: 'Luontoinventoinnin perusteet' },
    { code: 'YMPS6023', name: 'Ympäristöetiikka' },
    { code: 'YMPS6010', name: 'Ympäristöhistoria' },
    { code: 'YMPS6016', name: 'Ympäristösosiologia' },
    { code: 'YMPS1018', name: 'Ympäristönsuojelun valinnainen opintojakso' }

]

const run = async () => {
    console.log('*** RUNNING BOOTSTRAP ***')
    const subjectDomains = await Promise.all(subjects.map(async (s) => Subject.create({ subject_data: s })))
    courses.forEach(c => Course.create(
        { 
            subject_id: subjectDomains.find(sb => c.code.includes(sb.dataValues.subject_data.code)).dataValues.subject_id,
            course_data: c 
        }
    ))


}

module.exports = run